[package]
name = "googology"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "da420a8c6dd5bdfb85c4ced85c34388f633bc6ff"}
